# Generated by Django 6.0.5 on 2026-05-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel/Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Travel Platform')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('raw_value', models.FloatField()),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('raw_unit', models.CharField(blank=True, default='', max_length=50)),
                ('normalized_unit', models.CharField(blank=True, default='', max_length=50)),
                ('reporting_date', models.DateField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
